image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  GCP_ZONE: europe-west1-b

before_script:
  - export homedir=$(pwd)
  #- cd reddit
  #- bundle install

build_job:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - echo 'Building'
    - cd $homedir
    - docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
    - docker build -t ${DOCKER_USER}/reddit:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} docker-monolith
    - docker push ${DOCKER_USER}/reddit:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}

test_unit_job:
  before_script:
  - export homedir=$(pwd)
  - cd reddit
  - bundle install
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy review'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
   - branches
  except:
   - master

staging:
  stage: stage
  when: manual
  only:
   - /^\d+\.\d+\.\d+/
  script:
   - echo 'Deploy'
  environment:
   name: stage
   url: https://beta.example.com

production:
  stage: production
  only:
   - /^\d+\.\d+\.\d+/
  when: manual
  script:
   - echo 'Deploy'
  environment:
   name: production
   url: https://example.com