comment:
  image:
    repository: andreyovs/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: andreyovs/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: andreyovs/ui
    tag: latest
    service:
      externalPort: 9292