---
- name: Deploy to Docker
  hosts: tag_reddit-app
  become: true
  gather_facts: false

  tasks:
    - name: Deploy docker container from Docker Hub
      docker_container:
        name: reddit
        image: andreyovs/otus-reddit:1.0
        pull: yes
        state: started
        restart: yes
        ports:
        - "9292:9292"
