global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrey_ovsyannikov'
  email_configs:
  - to: mymail@gmail.com
    from: mymail@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "mymail@gmail.com"
    auth_identity: "mymail@gmail.com"
    auth_password: "app-token"

