FROM alpine:3.4

WORKDIR /app
COPY Gemfile* /app/

RUN \
    apk update \
    && apk upgrade \
    && apk add --no-cache --virtual build-dependencies ruby-dev build-base \
    && apk add --no-cache ruby ruby-bundler \
    && bundle config --global silence_root_warning 1 \
    && bundle install \
    && apk del build-dependencies

COPY . /app

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]

FROM ruby:2.2
RUN apt-get update -qq && apt-get install -y build-essential
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME
ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments
CMD ["puma"]