---
# tasks file for dockerhost
- name: Show info about install step
  debug:
   msg: "Deploy Docker"

- name: Ensure python-apt is installed
  command:
     apt-get install python-apt -y -q
     creates=/usr/share/doc/python-apt

- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: false

- block:

    - name: download get-pip.py
      get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp

    - name: install pip
      command: "python /tmp/get-pip.py"

    - name: delete get-pip.py
      file: state=absent path=/tmp/get-pip.py

  when: pip_is_installed.rc != 0

- name: Install docker-py
  pip:
    name: docker-py


- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
      name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
      state: present
      update_cache: yes
